Fixes for current version and upgrades (#41)
* Fixes for current version and upgrades

* Fixes for Cassandra dist url update

* Install dependencies

* Fix smoke test

* Fix Gpg keys

* Fix versions.yaml tags

diff --git a/templates/Dockerfile.template b/templates/Dockerfile.template
--- a/templates/Dockerfile.template
+++ b/templates/Dockerfile.template
@@ -27,7 +27,8 @@ ENV GOSU_VERSION {{ $gosu.Version }}
 ENV GOSU_GPG {{ $gosu.Gpg }}
 
 RUN set -x \
-	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/* \
+	&& apt-get update && apt-get install -y --no-install-recommends ca-certificates apt-transport-https wget \
+	&& rm -rf /var/lib/apt/lists/* \
 	&& wget -q -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
 	&& wget -q -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
 	&& wget -q -O /usr/local/src/gosu.tar.gz "https://github.com/tianon/gosu/archive/$GOSU_VERSION.tar.gz" \
@@ -36,35 +37,47 @@ RUN set -x \
 	&& gpg --no-tty --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
 	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
 	&& chmod +x /usr/local/bin/gosu \
-	&& gosu nobody true \
-	&& apt-get purge -y --auto-remove ca-certificates wget
+	&& gosu nobody true
 
-# solves warning: "jemalloc shared library could not be preloaded to speed up memory allocations"
-RUN apt-get update && apt-get install -y --no-install-recommends libjemalloc1 && rm -rf /var/lib/apt/lists/*
+RUN apt-get update \
+	&& apt-get install -y --no-install-recommends \
+		# solves warning: "jemalloc shared library could not be preloaded to speed up memory allocations"
+		libjemalloc1 \
+# "free" is used by cassandra-env.sh
+		procps \
+# "cqlsh" needs a python interpreter
+		python \
+# "ip" is not required by Cassandra itself, but is commonly used in scripting Cassandra's configuration (since it is so fixated on explicit IP addresses)
+		iproute2 \
+# Cassandra will automatically use numactl if available
+#   https://github.com/apache/cassandra/blob/18bcda2d4c2eba7370a0b21f33eed37cb730bbb3/bin/cassandra#L90-L100
+#   https://github.com/apache/cassandra/commit/604c0e87dc67fa65f6904ef9a98a029c9f2f865a
+		numactl \
+	&& rm -rf /var/lib/apt/lists/*
 
 # https://wiki.apache.org/cassandra/DebianPackaging#Adding_Repository_Keys
 ENV GPG_KEYS {{ $cassandra.Gpg }}
 
-RUN set -ex; \
-	export GNUPGHOME="$(mktemp -d)"; \
-	for key in $GPG_KEYS; do \
-		{{ `gpg --no-tty --keyserver $server --recv-keys "${key}"` | KeyServersRetryLoop "\t" }}; \
-	done; \
-	gpg --no-tty --export $GPG_KEYS > /etc/apt/trusted.gpg.d/cassandra.gpg; \
-	rm -rf "$GNUPGHOME"; \
-	apt-key list
-
-RUN echo {{ $cassandra.Version }} | sed 's-\([^.]\+\)\.\([^.]\+\).*$-deb http://www.apache.org/dist/cassandra/debian \1\2x main-' >> /etc/apt/sources.list.d/cassandra.list
-
 ENV CASSANDRA_VERSION {{ $cassandra.Version }}
+ENV CASSANDRA_SHA512 {{ $cassandra.Sha512 }}
+ENV CASSANDRA_HOME /opt/cassandra
+ENV CASSANDRA_CONFIG /etc/cassandra
+ENV PATH $CASSANDRA_HOME/bin:$PATH
 
 ENV C2D_RELEASE {{ $c2dRelease }}
 
-RUN set -x; \
-	if [ "${CASSANDRA_VERSION%%.*}" = "3" ]; then \
-		apt-get update && apt-get upgrade; \
-		apt-get install -y openjdk-8-jre-headless ntp; \
-	fi
+RUN set -ex; \
+	export DIST_FILE="https://archive.apache.org/dist/cassandra/{{ $cassandra.Version }}/apache-cassandra-{{ $cassandra.Version }}-bin.tar.gz"; \
+	wget --progress=dot:giga -O "cassandra-bin.tgz" "${DIST_FILE}"; \
+	echo "$CASSANDRA_SHA512 *cassandra-bin.tgz" | sha512sum --check --strict -
+
+RUN mkdir -p "$CASSANDRA_HOME"; \
+	tar --extract --file cassandra-bin.tgz --directory "$CASSANDRA_HOME" --strip-components 1; \
+	rm cassandra-bin.tgz*; \
+	\
+	[ ! -e "$CASSANDRA_CONFIG" ]; \
+	mv "$CASSANDRA_HOME/conf" "$CASSANDRA_CONFIG"; \
+	ln -sT "$CASSANDRA_CONFIG" "$CASSANDRA_HOME/conf"
 
 ENV JMX_EXPORTER_VERSION 0.11.0
 ENV JMX_EXPORTER_PATH /opt/jmx-exporter
@@ -83,24 +96,29 @@ RUN apt-get update \
 	&& wget -O $JMX_EXPORTER_LICENSE https://raw.githubusercontent.com/prometheus/jmx_exporter/master/LICENSE \
 	&& wget -O $JMX_EXPORTER_NOTICE https://raw.githubusercontent.com/prometheus/jmx_exporter/master/NOTICE \
 	&& apt-get purge -y --auto-remove ca-certificates wget \
-	&& apt-get install -y cassandra="$CASSANDRA_VERSION" \
 	&& rm -rf /var/lib/apt/lists/*
+
+RUN set -x; \
+	apt-get update && apt-get upgrade; \
+	apt-get install -y openjdk-8-jre-headless ntp
 
 # https://issues.apache.org/jira/browse/CASSANDRA-11661
 RUN sed -ri 's/^(JVM_PATCH_VERSION)=.*/\1=25/' /etc/cassandra/cassandra-env.sh
 
-ENV CASSANDRA_CONFIG /etc/cassandra
-
 COPY docker-entrypoint.sh /docker-entrypoint.sh
 ENTRYPOINT ["/docker-entrypoint.sh"]
 
-RUN mkdir -p /var/lib/cassandra "$CASSANDRA_CONFIG" \
-	&& chown -R cassandra:cassandra /var/lib/cassandra "$CASSANDRA_CONFIG" "$JMX_EXPORTER_PATH" \
-	&& chmod 777 /var/lib/cassandra "$CASSANDRA_CONFIG" "$JMX_EXPORTER_PATH"
+RUN mkdir -p /var/lib/cassandra "$CASSANDRA_CONFIG" /var/log/cassandra \
+	&& chown -R cassandra:cassandra /var/lib/cassandra "$CASSANDRA_CONFIG" "$JMX_EXPORTER_PATH" /var/log/cassandra \
+	&& chmod 777 /var/lib/cassandra "$CASSANDRA_CONFIG" "$JMX_EXPORTER_PATH" /var/log/cassandra \
+	&& ln -sT /var/lib/cassandra "$CASSANDRA_HOME/data" \
+	&& ln -sT /var/log/cassandra "$CASSANDRA_HOME/logs" \
+	&& chown cassandra:cassandra /docker-entrypoint.sh
+
 VOLUME /var/lib/cassandra
 
 RUN test ${C2D_RELEASE} = $(cassandra -v) \
-         || { echo "Version check failed"; exit 1; }
+        || { echo "Version check failed"; exit 1; }
 
 # 7000: intra-node communication
 # 7001: TLS intra-node communication
@@ -110,4 +128,3 @@ RUN test ${C2D_RELEASE} = $(cassandra -v) \
 # 9404: JMX Exporter for Prometheus metrics
 EXPOSE 7000 7001 7199 9042 9160 9404
 CMD ["cassandra", "-f"]
-
