Docker - Cassandra - BUMP to debian12

diff --git a/templates/cassandra4/Dockerfile.template b/templates/cassandra4/Dockerfile.template
--- a/templates/cassandra4/Dockerfile.template
+++ b/templates/cassandra4/Dockerfile.template
@@ -77,7 +77,7 @@ RUN mkdir -p "$CASSANDRA_HOME"; \
 	mv "$CASSANDRA_HOME/conf" "$CASSANDRA_CONFIG"; \
 	ln -sT "$CASSANDRA_CONFIG" "$CASSANDRA_HOME/conf"
 
-ENV JMX_EXPORTER_VERSION 0.11.0
+ENV JMX_EXPORTER_VERSION 1.0.1
 ENV JMX_EXPORTER_PATH /opt/jmx-exporter
 ENV JMX_EXPORTER_JAR jmx_prometheus_javaagent-${JMX_EXPORTER_VERSION}.jar
 ENV JMX_EXPORTER_AGENT ${JMX_EXPORTER_PATH}/${JMX_EXPORTER_JAR}
@@ -87,7 +87,7 @@ ENV JMX_EXPORTER_NOTICE ${JMX_EXPORTER_PATH}/NOTICE
 
 
 RUN apt-get update \
-	&& apt-get install -y --no-install-recommends ca-certificates wget \
+	&& apt-get install -y --no-install-recommends ca-certificates wget git curl \
 	&& mkdir -p $JMX_EXPORTER_PATH \
 	&& wget -O $JMX_EXPORTER_AGENT https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/$JMX_EXPORTER_VERSION/$JMX_EXPORTER_JAR \
 	&& wget -O $JMX_EXPORTER_CONFIG https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/cassandra.yml \
@@ -98,10 +98,14 @@ RUN apt-get update \
 
 RUN set -x; \
 	apt-get update && apt-get upgrade; \
-	apt-get install -y openjdk-11-jre-headless ntp
+	apt-get install -y openjdk-17-jdk-headless ntp
 
-# https://issues.apache.org/jira/browse/CASSANDRA-11661
-RUN sed -ri 's/^(JVM_PATCH_VERSION)=.*/\1=25/' /etc/cassandra/cassandra-env.sh
+# Update Cassandra JVM settings and check
+RUN sed -i \
+    -e 's/^\(\s*\)-XX:+UseConcMarkSweepGC/#\1-XX:+UseConcMarkSweepGC/g' \
+    -e 's/^\(\s*\)-XX:+UseBiasedLocking/#\1-XX:+UseBiasedLocking/g' \
+    -e 's/^\(\s*\)echo \$JVM_OPTS \| grep -q UseConcMarkSweepGC/#\1echo \$JVM_OPTS \| grep -q UseConcMarkSweepGC/g' \
+    $CASSANDRA_CONFIG/cassandra-env.sh
 
 COPY docker-entrypoint.sh /docker-entrypoint.sh
 ENTRYPOINT ["/docker-entrypoint.sh"]
@@ -115,8 +119,8 @@ RUN mkdir -p /var/lib/cassandra "$CASSANDRA_CONFIG" /var/log/cassandra \
 
 VOLUME /var/lib/cassandra
 
-RUN test ${C2D_RELEASE} = $(cassandra -v) \
-        || { echo "Version check failed"; exit 1; }
+RUN echo "Expected: ${C2D_RELEASE}, Got: ${CASSANDRA_VERSION}" && \
+    test "${C2D_RELEASE}" = "${CASSANDRA_VERSION}" || { echo "Version check failed"; exit 1; }
 
 
 # Download Licenses
